export { default as AnalyticsPage } from "./Analytics";
export { default as DashboardPage } from "./Dashboard";
export { default as InvoiceDetailsPage } from "./InvoiceDetails";
export { default as InvoicesPage } from "./Invoices";
export { default as PaymentsPage } from "./Payments";
export { default as PurchaseOrdersPage } from "./PurchaseOrders";
export { default as ReviewQueuePage } from "./Review";
export { default as UploadPage } from "./Upload";
export { default as VendorsPage } from "./Vendors";
